services:
  minio-server:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_admin_password
    volumes:
      - ./.docker-data/minio:/data
    networks:
      - backend-network
    command: server /data --console-address ":9001"
    restart: always

#  postgres:
#    image: postgres:16
#    container_name: postgres
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_DB: socialapp
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - ./.docker-data/postgres:/var/lib/postgresql/data
#      - ./docker/postgres/init:/docker-entrypoint-initdb.d
#    networks:
#      - backend-network
#    restart: always

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./.docker-data/opensearch:/usr/share/opensearch/data
    networks:
      - backend-network
    restart: always

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    networks:
      - backend-network
    depends_on:
      - opensearch
    restart: always

  neo4j:
    image: neo4j:5.20
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/neo4j_password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    volumes:
      - ./.docker-data/neo4j/data:/data
      - ./.docker-data/neo4j/logs:/logs
    networks:
      - backend-network
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker-data/redis:/data
    networks:
      - backend-network
    command: redis-server --save 60 1 --loglevel warning
    restart: always

networks:
  backend-network:
    driver: bridge
