-- =============================================================================================
-- 33 tin xu hướng, mỗi tin có nguồn, tác giả và tóm tắt riêng.

-- FILE NÀY SINH TỰ ĐỘNG bởi scripts/seed/generate_seed.py — sửa tay sẽ bị ghi đè.
--
-- KHÔNG CÓ PHẦN GITHUB STATS. Quyết định 25/08: không liên kết tài khoản nào với GitHub, nên
-- t_github_stats để trống hẳn. Hệ quả cần biết trước, không phải lỗi:
-- SkillVerificationService.verifyViaExternalApi tra bảng đó để tự xác minh kỹ năng, không có hàng
-- nào thì nhánh này LUÔN TRẢ FALSE và mọi yêu cầu xác minh kỹ năng rơi về duyệt tay. Với buổi demo
-- đây lại là điều tốt — hàng đợi quản trị có việc thật. (source GITHUB dưới đây là của tin xu hướng
-- crawl từ GitHub Trending, không liên quan gì tới t_github_stats.)
--
-- UNIQUE(source, source_id): source_id phải khác nhau từng dòng, nếu không chỉ chèn được một tin.
--
-- source lấy đúng BA HẰNG của TrendingSource (HACKER_NEWS, DEV_TO, GITHUB) — một hằng cho mỗi crawler
-- còn sống, KHÔNG có 'SEED'. Cột là varchar(50) không có CHECK nên một nhãn tự chế vẫn chèn được,
-- rồi nổ ở Hibernate lúc đọc và làm GET /v1/api/trending trả 500. Mỗi tin gắn nguồn tự nhiên của nó
-- (GitHub cho repo, dev.to cho bài blog, HN cho tin tổng hợp) thay vì rải nguồn theo vị trí.
--
-- author theo đúng thứ crawler thật ghi: HACKER_NEWS là handle người đăng, GITHUB là owner login,
-- DEV_TO là tên tác giả. image_url để NULL — HN cũng không có ảnh, và TrendingCrawlScheduler chạy
-- mỗi giờ sẽ lấp ảnh thật ngay khi BE online. Đây chỉ là bộ nền cho lúc offline / giờ đầu.
--
-- URL trỏ tin-tuc.example.test: .test là tên miền dành riêng, không định tuyến được (RFC 2606). Đổi
-- sang news.ycombinator.com hay dev.to sẽ cho ra liên kết trông thật rồi 404 khi bấm — tệ hơn một
-- liên kết thấy ngay là dữ liệu mẫu. Crawler thật ghi URL thật; bộ nền này thì không.

-- =============================================================================================

INSERT INTO socialapp.t_trending_items
    (title, summary, url, image_url, source, source_id, category, tags, score, author,
     published_at, crawled_at) VALUES
    ('Java 25 ra bản LTS, mặc định bật generational ZGC', 'Bản hỗ trợ dài hạn kế tiếp sau Java 21. Đáng chú ý nhất là ZGC thế hệ mới thành mặc định và structured concurrency rời khỏi preview.', 'https://tin-tuc.example.test/bai/1', NULL, 'HACKER_NEWS', 'seed-1', 'NEW_TECH', '["java","jvm","gc"]'::jsonb, 7184, 'todsacerdoti', now() - INTERVAL '74 days', now() - INTERVAL '74 days'),
    ('PostgreSQL 18: I/O bất đồng bộ và VACUUM nhanh hơn hẳn', 'io_uring cho đường đọc, cùng một lượt VACUUM gom được nhiều dead tuple hơn mỗi vòng. Người chạy bảng lớn nên đọc kỹ phần thay đổi cấu hình mặc định.', 'https://tin-tuc.example.test/bai/2', NULL, 'HACKER_NEWS', 'seed-2', 'NEW_TECH', '["postgresql","database","performance"]'::jsonb, 4411, 'tptacek', now() - INTERVAL '37 days', now() - INTERVAL '37 days'),
    ('Redis đổi giấy phép lần thứ hai trong hai năm', 'Bản mới quay lại một giấy phép gần với mã nguồn mở hơn sau làn sóng chỉ trích và sự ra đời của Valkey. Bài phân tích lại toàn bộ dòng thời gian.', 'https://tin-tuc.example.test/bai/3', NULL, 'HACKER_NEWS', 'seed-3', 'REGULATION', '["redis","license","opensource"]'::jsonb, 9284, 'ingve', now() - INTERVAL '42 days', now() - INTERVAL '42 days'),
    ('Kubernetes 1.34 gỡ bỏ vài API đã đánh dấu lỗi thời từ lâu', 'Danh sách API bị gỡ và cách dò trong cụm trước khi nâng cấp. Vài Helm chart phổ biến vẫn còn tham chiếu phiên bản cũ.', 'https://tin-tuc.example.test/bai/4', NULL, 'HACKER_NEWS', 'seed-4', 'NEW_TECH', '["kubernetes","devops","migration"]'::jsonb, 3930, 'mooreds', now() - INTERVAL '52 days', now() - INTERVAL '52 days'),
    ('polars — DataFrame trên Rust, API giống pandas', 'Thư viện xử lý dữ liệu dạng cột, chạy song song và lười đánh giá. Bản mới thêm streaming engine cho tập dữ liệu lớn hơn RAM.', 'https://tin-tuc.example.test/bai/5', NULL, 'GITHUB', 'seed-5', 'OPENSOURCE', '["rust","python","data"]'::jsonb, 9138, 'pola-rs', now() - INTERVAL '35 days', now() - INTERVAL '35 days'),
    ('bun — runtime JavaScript gộp cả bundler và test runner', 'Bản mới tập trung vào tương thích Node và tốc độ cài phụ thuộc. Nhiều dự án chuyển CI sang bun chỉ để rút ngắn bước install.', 'https://tin-tuc.example.test/bai/6', NULL, 'GITHUB', 'seed-6', 'OPENSOURCE', '["javascript","nodejs","tooling"]'::jsonb, 2647, 'oven-sh', now() - INTERVAL '42 days', now() - INTERVAL '42 days'),
    ('duckdb — cơ sở dữ liệu phân tích chạy trong tiến trình', 'SQLite cho phân tích: một file, không server, đọc thẳng Parquet và CSV. Bản mới cải thiện bộ nhớ khi join tập lớn.', 'https://tin-tuc.example.test/bai/7', NULL, 'GITHUB', 'seed-7', 'OPENSOURCE', '["database","analytics","sql"]'::jsonb, 8710, 'duckdb', now() - INTERVAL '46 days', now() - INTERVAL '43 days'),
    ('Nhiều đội quay lại monolith sau vài năm microservices', 'Ghi lại quá trình gộp mười hai dịch vụ về ba, và những chi phí ẩn của microservices mà sơ đồ kiến trúc không cho thấy.', 'https://tin-tuc.example.test/bai/8', NULL, 'DEV_TO', 'seed-8', 'MINDSET', '["architecture","microservices","monolith"]'::jsonb, 4619, 'Nguyễn Minh Đức', now() - INTERVAL '21 days', now() - INTERVAL '18 days'),
    ('Có nên viết test cho đoạn mã sắp bị xoá?', 'Lập luận cho cả hai phía, và một quy tắc đơn giản: test để mã đổi được an toàn, nên mã không đổi nữa thì test cũng hết việc.', 'https://tin-tuc.example.test/bai/9', NULL, 'DEV_TO', 'seed-9', 'MINDSET', '["testing","mindset","refactoring"]'::jsonb, 8222, 'Trần Thu Hà', now() - INTERVAL '66 days', now() - INTERVAL '66 days'),
    ('Đọc query plan trước khi thêm index', 'Hướng dẫn từng bước đọc EXPLAIN ANALYZE của Postgres, kèm bốn dấu hiệu cho biết index sẽ không giúp gì.', 'https://tin-tuc.example.test/bai/10', NULL, 'DEV_TO', 'seed-10', 'TOOL', '["postgresql","performance","database"]'::jsonb, 4206, 'Phạm Quốc Bảo', now() - INTERVAL '73 days', now() - INTERVAL '73 days'),
    ('Xoay vòng khoá bí mật mà không gián đoạn dịch vụ', 'Mẫu hai khoá song song: phát khoá mới, chấp nhận cả hai trong thời gian chuyển tiếp, rồi mới thu hồi khoá cũ. Kèm ví dụ cho JWT và khoá API.', 'https://tin-tuc.example.test/bai/11', NULL, 'DEV_TO', 'seed-11', 'TOOL', '["security","secrets","operations"]'::jsonb, 4079, 'Lê Hoàng Nam', now() - INTERVAL '66 days', now() - INTERVAL '63 days'),
    ('uv — trình quản lý gói Python viết bằng Rust', 'Thay thế pip và virtualenv, giải phụ thuộc nhanh hơn nhiều lần. Bản mới thêm khoá phiên bản khoá liên nền tảng.', 'https://tin-tuc.example.test/bai/12', NULL, 'GITHUB', 'seed-12', 'TOOL', '["python","packaging","tooling"]'::jsonb, 8854, 'astral-sh', now() - INTERVAL '45 days', now() - INTERVAL '43 days'),
    ('Báo cáo lương ngành phần mềm Việt Nam nửa cuối năm', 'Tổng hợp từ hơn ba nghìn phản hồi: mức trung vị theo cấp bậc, chênh lệch giữa các thành phố, và tác động của làm việc từ xa lên lương.', 'https://tin-tuc.example.test/bai/13', NULL, 'HACKER_NEWS', 'seed-13', 'CAREER', '["career","salary","vietnam"]'::jsonb, 1320, 'mooreds', now() - INTERVAL '32 days', now() - INTERVAL '29 days'),
    ('Thị trường tuyển dụng nghiêng về kỹ sư đa năng', 'Phân tích tin tuyển dụng trong sáu tháng: số vị trí đòi cả hai đầu tăng, số vị trí chuyên sâu một mảng giảm. Kèm góc nhìn nên phản ứng thế nào.', 'https://tin-tuc.example.test/bai/14', NULL, 'DEV_TO', 'seed-14', 'CAREER', '["career","hiring","fullstack"]'::jsonb, 7269, 'Đỗ Thị Lan', now() - INTERVAL '10 days', now() - INTERVAL '10 days'),
    ('Phỏng vấn kỹ thuật không hỏi thuật toán', 'Một quy trình dựa trên bài tập sát việc thật và đọc mã có sẵn, cùng dữ liệu cho thấy nó dự đoán hiệu quả công việc tốt hơn.', 'https://tin-tuc.example.test/bai/15', NULL, 'DEV_TO', 'seed-15', 'CAREER', '["career","interview","hiring"]'::jsonb, 8218, 'Vũ Đình Khoa', now() - INTERVAL '38 days', now() - INTERVAL '38 days'),
    ('Hội thảo Vietnam Web Summit mở đăng ký', 'Sự kiện thường niên về kỹ thuật web, năm nay có nhánh riêng cho hiệu năng và khả năng truy cập. Vé sớm giới hạn số lượng.', 'https://tin-tuc.example.test/bai/16', NULL, 'HACKER_NEWS', 'seed-16', 'EVENT', '["event","web","conference"]'::jsonb, 591, 'ingve', now() - INTERVAL '54 days', now() - INTERVAL '52 days'),
    ('GopherCon công bố danh sách diễn giả', 'Chủ đề tập trung vào công cụ, hồ sơ hiệu năng và các thay đổi sắp tới của bộ thu gom rác trong Go.', 'https://tin-tuc.example.test/bai/17', NULL, 'HACKER_NEWS', 'seed-17', 'EVENT', '["event","golang","conference"]'::jsonb, 6853, 'todsacerdoti', now() - INTERVAL '62 days', now() - INTERVAL '59 days'),
    ('htmx 2.0: bớt JavaScript, trả HTML từ máy chủ', 'Bản chính thức của cách tiếp cận ''hypermedia làm trung tâm''. Bài viết so sánh thẳng với một ứng dụng SPA tương đương về dòng mã và thời gian tải.', 'https://tin-tuc.example.test/bai/18', NULL, 'HACKER_NEWS', 'seed-18', 'NEW_TECH', '["frontend","htmx","web"]'::jsonb, 5333, 'tptacek', now() - INTERVAL '75 days', now() - INTERVAL '75 days'),
    ('SQLite thêm chế độ ghi đồng thời nhiều tiến trình', 'Tính năng thử nghiệm cho phép nhiều tiến trình ghi mà không khoá toàn bộ file. Vẫn còn cảnh báo rõ ràng về phạm vi dùng.', 'https://tin-tuc.example.test/bai/19', NULL, 'HACKER_NEWS', 'seed-19', 'NEW_TECH', '["sqlite","database","concurrency"]'::jsonb, 5078, 'ingve', now() - INTERVAL '61 days', now() - INTERVAL '60 days'),
    ('OWASP cập nhật danh sách Top 10 rủi ro ứng dụng web', 'Lỗi cấu hình và lỗ hổng chuỗi cung ứng leo hạng. Bài viết đối chiếu từng mục với các sự cố có thật trong năm.', 'https://tin-tuc.example.test/bai/20', NULL, 'HACKER_NEWS', 'seed-20', 'REGULATION', '["security","owasp","appsec"]'::jsonb, 5051, 'tptacek', now() - INTERVAL '60 days', now() - INTERVAL '57 days'),
    ('Quy định mới về lưu trữ dữ liệu người dùng trong nước', 'Tóm tắt phần liên quan tới đội kỹ thuật: dữ liệu nào phải đặt máy chủ trong nước, thời hạn chuyển đổi, và ảnh hưởng lên lựa chọn nhà cung cấp đám mây.', 'https://tin-tuc.example.test/bai/21', NULL, 'DEV_TO', 'seed-21', 'REGULATION', '["regulation","data","compliance"]'::jsonb, 6834, 'Hoàng Anh Tuấn', now() - INTERVAL '8 days', now() - INTERVAL '7 days'),
    ('tokio — runtime bất đồng bộ cho Rust', 'Bản mới cải thiện bộ lập lịch tác vụ và thêm công cụ theo dõi tác vụ bị treo. Nền tảng của phần lớn dịch vụ mạng viết bằng Rust.', 'https://tin-tuc.example.test/bai/22', NULL, 'GITHUB', 'seed-22', 'OPENSOURCE', '["rust","async","networking"]'::jsonb, 7185, 'tokio-rs', now() - INTERVAL '26 days', now() - INTERVAL '24 days'),
    ('ripgrep — tìm chuỗi trong mã nhanh hơn grep', 'Công cụ dòng lệnh tôn trọng .gitignore và quét song song. Bài viết của tác giả giải thích các lựa chọn thiết kế đứng sau tốc độ.', 'https://tin-tuc.example.test/bai/23', NULL, 'GITHUB', 'seed-23', 'OPENSOURCE', '["cli","rust","tooling"]'::jsonb, 8860, 'BurntSushi', now() - INTERVAL '72 days', now() - INTERVAL '69 days'),
    ('Đo p99 thay vì trung bình, và vì sao điều đó quan trọng', 'Một request chậm trong một trăm vẫn là một phần trăm người dùng bực bội. Bài viết chỉ cách dựng biểu đồ phân vị và đọc nó.', 'https://tin-tuc.example.test/bai/24', NULL, 'DEV_TO', 'seed-24', 'MINDSET', '["performance","observability","metrics"]'::jsonb, 2058, 'Ngô Phương Linh', now() - INTERVAL '19 days', now() - INTERVAL '16 days'),
    ('Ghi lại quyết định kiến trúc bằng một trang mỗi lần', 'Mẫu ADR gọn: bối cảnh, lựa chọn, hệ quả, phương án đã loại. Đội mới vào đọc lại hiểu vì sao hệ thống thành ra như bây giờ.', 'https://tin-tuc.example.test/bai/25', NULL, 'DEV_TO', 'seed-25', 'MINDSET', '["architecture","documentation","team"]'::jsonb, 4395, 'Bùi Thanh Sơn', now() - INTERVAL '5 days', now() - INTERVAL '3 days'),
    ('k6 — kiểm thử tải viết bằng JavaScript', 'Kịch bản tải viết như mã thường, chạy được trong CI. Bản mới thêm báo cáo ngưỡng rõ ràng hơn khi tích hợp pipeline.', 'https://tin-tuc.example.test/bai/26', NULL, 'GITHUB', 'seed-26', 'TOOL', '["testing","performance","load-testing"]'::jsonb, 6685, 'grafana', now() - INTERVAL '73 days', now() - INTERVAL '71 days'),
    ('OpenTelemetry ổn định phần logs, khép lại bộ ba tín hiệu', 'Sau metrics và traces, đặc tả logs đạt mốc ổn định. Nhiều thư viện bắt đầu bỏ định dạng log riêng để theo chuẩn chung.', 'https://tin-tuc.example.test/bai/27', NULL, 'HACKER_NEWS', 'seed-27', 'NEW_TECH', '["observability","opentelemetry","logging"]'::jsonb, 218, 'mooreds', now() - INTERVAL '11 days', now() - INTERVAL '10 days'),
    ('Terraform và cuộc dịch chuyển sang OpenTofu', 'Một năm sau khi tách nhánh, bài viết tổng kết số dự án đã chuyển, khác biệt tính năng và những gì cần lưu ý khi di trú state.', 'https://tin-tuc.example.test/bai/28', NULL, 'HACKER_NEWS', 'seed-28', 'REGULATION', '["terraform","opentofu","infrastructure"]'::jsonb, 2996, 'todsacerdoti', now() - INTERVAL '44 days', now() - INTERVAL '44 days'),
    ('Zed — trình soạn thảo mã viết bằng Rust, mở mã nguồn', 'Tập trung vào độ trễ gõ phím và cộng tác thời gian thực. Bản mới thêm hỗ trợ gỡ lỗi tích hợp cho vài ngôn ngữ.', 'https://tin-tuc.example.test/bai/29', NULL, 'GITHUB', 'seed-29', 'OPENSOURCE', '["editor","rust","tooling"]'::jsonb, 1778, 'zed-industries', now() - INTERVAL '58 days', now() - INTERVAL '58 days'),
    ('Học trong ngành: chọn thứ đáng học, bỏ qua thứ đang ồn ào', 'Khung ra quyết định học cái gì: nền tảng lâu bền trước, công cụ theo nhu cầu công việc sau, và cách nhận ra một xu hướng sẽ không trụ được.', 'https://tin-tuc.example.test/bai/30', NULL, 'DEV_TO', 'seed-30', 'CAREER', '["career","learning","mindset"]'::jsonb, 7984, 'Trịnh Gia Hân', now() - INTERVAL '46 days', now() - INTERVAL '44 days'),
    ('Cách một đội nhỏ vận hành hạ tầng mà không cần trực đêm', 'Ghi chép về việc chọn dịch vụ quản lý thay vì tự vận hành, đặt cảnh báo hành động được, và viết runbook cho ba sự cố hay gặp nhất.', 'https://tin-tuc.example.test/bai/31', NULL, 'DEV_TO', 'seed-31', 'OTHER', '["operations","devops","team"]'::jsonb, 2590, 'Lý Tuấn Kiệt', now() - INTERVAL '27 days', now() - INTERVAL '25 days'),
    ('Vì sao build CI của bạn chậm, và bốn cách rút ngắn', 'Phân tích một pipeline mười tám phút xuống còn sáu: cache phụ thuộc, chạy song song, bỏ bước trùng, và tách test chậm ra nhánh riêng.', 'https://tin-tuc.example.test/bai/32', NULL, 'DEV_TO', 'seed-32', 'OTHER', '["cicd","performance","tooling"]'::jsonb, 7438, 'Nguyễn Hải Đăng', now() - INTERVAL '59 days', now() - INTERVAL '57 days'),
    ('caddy — web server tự động cấp chứng chỉ HTTPS', 'Cấu hình ngắn, HTTPS bật sẵn không cần thao tác. Bản mới cải thiện reverse proxy và thêm chỉ số Prometheus mặc định.', 'https://tin-tuc.example.test/bai/33', NULL, 'GITHUB', 'seed-33', 'OPENSOURCE', '["web-server","https","devops"]'::jsonb, 3377, 'caddyserver', now() - INTERVAL '20 days', now() - INTERVAL '20 days');

SELECT setval('socialapp.q_trending_items_id',
              GREATEST((SELECT COALESCE(MAX(id), 0) FROM socialapp.t_trending_items), 1), true);
