package com.socialapp.knowledge.service;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;

import com.socialapp.knowledge.dto.ExplanationResponseDto.ExternalLink;

/**
 * Drops the "further reading" links a model produced that a reader could not follow anyway.
 *
 * <p>Nothing on either side fetches these links (see the note at the top of the frontend's {@code
 * explanation-card.tsx}), so this is a <em>syntactic</em> filter, not a liveness check — but it
 * catches the failure that actually happened (backend-plan B34, measured 31/08/2026): a Datadog
 * blog URL with Tamil script spliced into the path. A URL a model emits to be clicked is ASCII —
 * an internationalised host arrives punycoded, an internationalised path percent-encoded — so raw
 * non-ASCII in the string means the model corrupted it mid-generation, and {@link URI} will not
 * reject it (it just carries the bytes). This is the backend copy of the frontend's {@code
 * isFollowableLink}: applied here too so the saved explanation and any non-browser client are
 * covered, not only the one screen.
 *
 * <p>What this does NOT catch: a well-formed URL that is simply wrong — a real host, a plausible
 * path, a 404 anyway, or a mismatched title. That needs a request per link on an endpoint already
 * seconds slow, and the card's "generated by AI, verify it" banner is the mitigation for it.
 */
final class ExternalLinkSanitizer {

  private ExternalLinkSanitizer() {}

  /** The model's links, minus the ones that will not resolve. Order preserved. */
  static List<ExternalLink> followable(List<ExternalLink> links) {
    if (links == null || links.isEmpty()) {
      return List.of();
    }
    return links.stream().filter(ExternalLinkSanitizer::isFollowable).toList();
  }

  private static boolean isFollowable(ExternalLink link) {
    if (link == null || link.getUrl() == null) {
      return false;
    }
    String raw = link.getUrl().trim();
    if (raw.isEmpty()) {
      return false;
    }

    // Anything outside printable ASCII is the hallucination tell — one check covers the spliced-in
    // non-Latin script and any stray control character.
    for (int i = 0; i < raw.length(); i++) {
      char c = raw.charAt(i);
      if (c < 0x20 || c > 0x7E) {
        return false;
      }
    }

    URI parsed;
    try {
      parsed = new URI(raw);
    } catch (URISyntaxException e) {
      return false;
    }

    String scheme = parsed.getScheme();
    if (scheme == null || !("http".equalsIgnoreCase(scheme) || "https".equalsIgnoreCase(scheme))) {
      return false;
    }

    // A host with no dot ("localhost", "intranet") is not a public further-reading target.
    String host = parsed.getHost();
    return host != null && host.contains(".");
  }
}
